name: ✨ Feature request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Great ideas welcome. Context + examples help a lot.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to achieve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like the API/behavior to look like?
      placeholder: |
        Example API:
        ```ts
        // sketch here
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other libraries you tried?
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, links, prior art, edge cases.
    validations:
      required: false
